---
MD007:
  indent: 4 # only 4 indentation can be recognized as a sublist by mkdocs
MD013: false # no need to limit line length
MD046: false # fenced code blocks is prefered, but admonition syntax requires indentation