site_name: Fims Proto
repo_url: http://github.com/fims-proto/documentations

nav:
  - Home: "index.md"
  - Backend:
    - SoB:
      - "backend/sob/index.md"
      - Create SoB: "backend/sob/create_sob.md"
    - General Ledger:
      - "backend/general_ledger/index.md"
      - Close Period: "backend/general_ledger/close_period.md"
    - Report:
      - "backend/report/index.md"
      - Draft samples: "backend/report/samples.md"
      - When to Save Report: "backend/report/save_report.md"
  - Go to Production:
    - Todo List: "go_to_production/todos.md"
  - Archived:
    - Design: "archived/design.md"
  - About: "about.md"

theme:
  name: material

  icon:
    repo: fontawesome/brands/github
  
  features:
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - navigation.sections
    - content.tooltips
  
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/theme-light-dark
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

plugins:
    - search

markdown_extensions:
  - admonition
  - pymdownx.critic
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format